### ISSUE TITLE
Install triwise on a Mac requires R => 3.4 (?) 

### ISSUE THREAD

**Issue by cartal** [saeyslab/triwise#1]
Hi!

I'm trying to install triwise on my Mac with Rstudio (R-3.3.2) as follows:

devtools::install_github("saeyslab/triwise")

But I get the following error:

`Downloading GitHub repo saeyslab/triwise@master
from URL https://api.github.com/repos/saeyslab/triwise/zipball/master
Installing triwise
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL 
'/private/var/folders/w0/ryk3_mg12sb2t0fnp98v_0hjh33t8d/T/Rtmp8Oyw8d/devtoolsc6881e72e525/saeyslab-triwise-ac7550e' --library='/Users/talavec/Library/R/3.3/library' 
--install-tests

ERROR: this R is version 3.3.2, package 'triwise' requires R >= 3.4
Error: Command failed (1)`

As far as I know, R is available up to version 3.2.2 for Mac. Unless I'm missing something obvious.

**Comment by zouter** [comment]
You are correct that the most recent version of R for Mac (or any platform) is 3.3.X . I downgraded the requirement again so it should be installable for you. 

(R version >= 3.4 was necessary for submission to the current bioconductor release cycle).
